@baseUrl = http://localhost:8890

### GET /hello
GET {{baseUrl}}/greet

### GET /hello

GET {{baseUrl}}/greet?name=bob
Accept: application/json


### GET /hello

GET {{baseUrl}}/greet
Accept: application/edn


### GET /info

GET {{baseUrl}}/info
Accept: application/json

### GET /config

GET {{baseUrl}}/config


### GET /explore (default)

GET {{baseUrl}}/explore
Accept: application/edn

### GET /explore

GET {{baseUrl}}/explore?dir=barcode
Accept: application/edn

