@baseUrl = http://localhost:8890

### GET /hello
GET {{baseUrl}}/greet

### GET /hello

GET {{baseUrl}}/greet?name=bob
Accept: application/json


### GET /hello

GET {{baseUrl}}/greet
Accept: application/edn


### GET /info

GET {{baseUrl}}/info
Accept: application/json

### GET /config

GET {{baseUrl}}/config
Accept: application/edn

### GET /explore (default)

GET {{baseUrl}}/explore
Accept: application/edn

### GET /explore

GET {{baseUrl}}/explore?dir=barcode
Accept: application/edn

### GET /download

GET {{baseUrl}}/download?path=package.json&disposition=inline

### GET /index

GET {{baseUrl}}/index?type=dir

### GET /event

GET {{baseUrl}}/event

### GET /open

GET {{baseUrl}}/open?path=README.txt

### GET /cmd

GET {{baseUrl}}/cmd?path=README.txt&name=open

